# Generated by Django 5.2.6 on 2026-05-09 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('cover_image', models.ImageField(blank=True, upload_to='series/')),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='characters/')),
                ('role', models.CharField(choices=[('Hero', 'Hero'), ('Villain', 'Villain'), ('Sidekick', 'Sidekick')], max_length=50)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='SPCapp.series')),
            ],
        ),
    ]
